# Generated by Django 4.1.1 on 2022-11-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_post_follow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
    ]
